#####################################################################
# MENU PRINCIPAL
#####################################################################

[menu __main services]
name: Services
icon: settings

#####################################################################
# PRECHAUFFAGE
#####################################################################

[menu __main services preppla]
name: Préchauffage
icon: heat-up
method: printer.gcode.script
params: {"script":"PREP_PLA"}

[menu __main services fullpla]
name: Préchauffage Full
icon: heat-up
method: printer.gcode.script
params: {"script":"FULL_PLA"}

#####################################################################
# CALIBRATION
#####################################################################

[menu __main services pa]
name: PA Calibration
icon: settings
method: printer.gcode.script
params: {"script":"PRESSURE_ADVANCE_CALIBRATION"}

[menu __main services flow]
name: Flow Calibration
icon: settings
method: printer.gcode.script
params: {"script":"FLOW_MULTIPLIER_CALIBRATION"}

[menu __main services computeflow]
name: Compute Flow
icon: settings
method: printer.gcode.script
params: {"script":"COMPUTE_FLOW_MULTIPLIER"}

#####################################################################
# SAUVEGARDE
#####################################################################

[menu __main services github]
name: Save GitHub
icon: refresh
method: printer.gcode.script
params: {"script":"SAUVE_GITHUB"}


#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-dark
#~# only_heaters = True
#~# print_sort_dir = date_desc
#~# language = fr
#~#
