#####################################################################
# MENU PRINCIPAL
#####################################################################

[menu __main macros]
name: Services
icon: settings

#####################################################################
# CONTENU DU MENU MACROS
#####################################################################

[menu __main macros preppla]
name: Préchauffage
icon: heat-up
method: printer.gcode.script
params: {"script":"PREP_PLA"}

[menu __main macros fullpla]
name: Préchauffage (Full)
icon: heat-up
method: printer.gcode.script
params: {"script":"FULL_PLA"}

[menu __main macros savegitbub]
name: Save GitHub
icon: heat-up
method: printer.gcode.script
params: {"script":"SAUVE_GITHUB"}

[menu __main macros PRESSURE_ADVANCE_CALIBRATION]
name: PA Calibration
icon: heat-up
method: printer.gcode.script
params: {"script":"PRESSURE_ADVANCE_CALIBRATION"}

[menu __main macros FLOW_MULTIPLIER_CALIBRATION]
name: Flow Calibration
icon: heat-up
method: printer.gcode.script
params: {"script":"FLOW_MULTIPLIER_CALIBRATION"}

[menu __main macros COMPUTE_FLOW_MULTIPLIER]
name: Compute flow multiplier
icon: heat-up
method: printer.gcode.script
params: {"script":"COMPUTE_FLOW_MULTIPLIER"}


#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-dark
#~# only_heaters = True
#~# print_sort_dir = date_desc
#~# language = fr
#~#
